# Generated by Django 3.0.7 on 2020-07-22 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='tasks',
            new_name='taskIds',
        ),
    ]
